alias case-camel-kebab="sed -r -e 's/([A-Z])/-\L\1/g'"
alias cc="xclip -selection clipboard"
alias cu="chromium --disable-web-security --user-data-dir=$HOME/chromium-unsafe"
alias cv="xclip -selection clipboard -out"
alias dog="highlight -O ansi"
alias g="git log --oneline -n 5 && git status --short"
alias gb="git branch -vv"
alias gl="git log --oneline"
alias glm="git log --oneline origin/master.."
alias ll="ls -ahl"
alias ll="ls -alh"
alias x="xdg-open"
